// Daily content-pool publishing (brief §11), shared by the server's built-in
// scheduler and the manual CLI (scripts/generate-daily-pool.js).
//
// Content source: Gemini when GEMINI_API_KEY is set, otherwise (or on any
// Gemini failure) the sampleVariants from the experiment config. Either way
// the pool always publishes, so POOL_MISSING can only mean "not generated
// yet", never "generation broke".
//
// Concurrency: an advisory transaction lock keyed on the day serializes
// simultaneous publishes from any number of pods; the existence check inside
// the lock makes re-runs no-ops.
import { query, withTx } from './db.js';
import { todayKey, weekdayName } from './day.js';
import { geminiEnabled, generateChaptersWithGemini } from './gemini.js';

export function buildAnchor(cfg, day) {
  const weekday = weekdayName(new Date(`${day}T12:00:00+05:30`));
  return cfg.anchorsByWeekday[weekday] || { label: weekday, detail: '' };
}

async function generateItems(cfg, day) {
  const anchor = buildAnchor(cfg, day);
  const weekday = weekdayName(new Date(`${day}T12:00:00+05:30`));
  if (geminiEnabled()) {
    try {
      const chapters = await generateChaptersWithGemini(cfg, day, weekday, anchor);
      console.log(`[pool] ${day}: content generated by Gemini`);
      return chapters;
    } catch (err) {
      console.error(`[pool] ${day}: Gemini generation failed (${err.message}) — falling back to config sample content`);
    }
  } else {
    console.log(`[pool] ${day}: GEMINI_API_KEY not set — using config sample content`);
  }
  return cfg.chapters.map((chapter) => chapter.sampleVariants);
}

export async function publishPool(cfg, day, { force = false } = {}) {
  // Generate BEFORE opening the transaction — Gemini can take many seconds
  // and must not hold DB locks while it thinks.
  const perChapter = await generateItems(cfg, day);
  const anchor = buildAnchor(cfg, day);

  return withTx(async (client) => {
    await client.query('SELECT pg_advisory_xact_lock(hashtext($1))', [`daily-cast-pool-${day}`]);

    const existing = await client.query('SELECT 1 FROM content_pool_days WHERE day = $1', [day]);
    if (existing.rowCount > 0) {
      if (!force) return { published: false, reason: 'exists' };
      const used = await client.query(
        'SELECT count(*)::int AS n FROM user_daily_states WHERE day = $1 AND casts_used > 0',
        [day],
      );
      if (used.rows[0].n > 0) {
        throw new Error(
          `refusing --force: ${used.rows[0].n} user(s) already cast on ${day}; replacing the pool would break their stable readings`,
        );
      }
      await client.query('DELETE FROM content_pool_days WHERE day = $1', [day]);
      console.log(`[pool] --force: replaced existing (unused) pool for ${day}`);
    }

    await client.query(
      'INSERT INTO content_pool_days (day, anchor) VALUES ($1, $2)',
      [day, JSON.stringify(anchor)],
    );

    let itemId = 0;
    for (let chapterIndex = 0; chapterIndex < perChapter.length; chapterIndex++) {
      for (const variant of perChapter[chapterIndex]) {
        itemId += 1;
        await client.query(
          `INSERT INTO content_pool_items (day, item_id, chapter_index, body, open_question)
           VALUES ($1, $2, $3, $4, $5)`,
          [day, itemId, chapterIndex, variant.body, variant.openQuestion ?? null],
        );
      }
    }

    console.log(`[pool] published pool for ${day}: ${itemId} items across ${perChapter.length} chapters`);
    return { published: true, total: itemId };
  });
}

// Cheap idempotent guard used by the server: after the first success for a
// given day it costs nothing (in-memory check); at day rollover it publishes
// the new day's pool exactly once even under concurrent callers.
let ensuredDay = null;
let inflight = null;

export async function ensurePoolForToday(cfg) {
  const day = todayKey();
  if (ensuredDay === day) return day;
  if (!inflight) {
    inflight = (async () => {
      const { rows } = await query('SELECT 1 FROM content_pool_days WHERE day = $1', [day]);
      if (rows.length === 0) await publishPool(cfg, day);
      ensuredDay = day;
    })().finally(() => { inflight = null; });
  }
  await inflight;
  return day;
}
